<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Version>0.1.0</Version>
    <Authors>Martin Strand</Authors>
    <Product>MissingFiles</Product>
    <Copyright>Copyright (c) Martin Strand</Copyright>
  </PropertyGroup>
</Project>
